smol = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""

p1 = p2 = 0

with open("./2025/07/input.txt", "r") as f:
    grid = [s.strip() for s in f.readlines()]

# grid = smol.split("\n")

beams = {}
beams[grid[0].index("S")] = 1
for line in grid[::2]:
    for i in list(beams.keys()):
        if line[i] == "^":
            p1 += 1
            beams[i-1] = beams.get(i-1, 0) + beams[i]
            beams[i+1] = beams.get(i+1, 0) + beams[i]
            del beams[i]

print(f"Part 1: {p1}")
print(f"Part 2: {sum(beams.values())}")
